"""Immutable, policy-bound workflow definitions and release pointers.

This package is deliberately a definition/control boundary.  It does not
claim, lease, execute, or complete work.  A resolved definition is eventually
materialized through the native ``WorkItem`` protocol, which remains the sole
execution authority.
"""

from .domain import (
    ABSOLUTE_MAX_COST_MICROS,
    ABSOLUTE_MAX_DEPTH,
    ABSOLUTE_MAX_FANOUT,
    ABSOLUTE_MAX_SECONDS,
    ABSOLUTE_MAX_STEPS,
    ABSOLUTE_MAX_TOKENS,
    ApprovedBinding,
    ArtifactRef,
    BindingKind,
    ChannelName,
    Digest,
    StepContract,
    WorkflowBudget,
    WorkflowDefinition,
    WorkflowGraphStats,
    WorkflowIdentity,
    WorkflowResolution,
    WorkflowStep,
    WorkflowSummary,
    WorkflowTemplate,
    WorkflowVersion,
    canonical_definition,
    definition_digest,
    resolution_digest,
)
from .repository import (
    BindingRegistry,
    ExactBindingRegistry,
    InMemoryWorkflowRepository,
    RejectAllBindingRegistry,
    ReleasePointer,
    WorkflowCatalog,
    WorkflowConflictError,
    WorkflowDomainError,
    WorkflowNotFoundError,
    WorkflowRepository,
)

__all__ = [
    "ABSOLUTE_MAX_COST_MICROS",
    "ABSOLUTE_MAX_DEPTH",
    "ABSOLUTE_MAX_FANOUT",
    "ABSOLUTE_MAX_SECONDS",
    "ABSOLUTE_MAX_STEPS",
    "ABSOLUTE_MAX_TOKENS",
    "ApprovedBinding",
    "ArtifactRef",
    "BindingKind",
    "BindingRegistry",
    "ChannelName",
    "Digest",
    "ExactBindingRegistry",
    "InMemoryWorkflowRepository",
    "RejectAllBindingRegistry",
    "ReleasePointer",
    "StepContract",
    "WorkflowBudget",
    "WorkflowCatalog",
    "WorkflowConflictError",
    "WorkflowDefinition",
    "WorkflowDomainError",
    "WorkflowGraphStats",
    "WorkflowIdentity",
    "WorkflowNotFoundError",
    "WorkflowRepository",
    "WorkflowResolution",
    "WorkflowStep",
    "WorkflowSummary",
    "WorkflowTemplate",
    "WorkflowVersion",
    "canonical_definition",
    "definition_digest",
    "resolution_digest",
]
