"""Tenant-safe, generation-bound retrieval control plane."""

from .errors import (
    CleanupIncompleteError,
    GenerationConflictError,
    GenerationNotFoundError,
    RetrievalAuthorizationError,
    RetrievalDomainError,
    RetrievalReplayError,
    StaleGenerationError,
)
from .models import (
    MAX_CITATIONS,
    MAX_EVALUATION_METRICS,
    MAX_HITS,
    MAX_INDEX_CHUNKS,
    ArtifactRef,
    AuthorizationEvidence,
    ChunkRef,
    CitationRecord,
    CitationRef,
    CleanupCheckpoint,
    DocumentRef,
    EmbeddingModelRef,
    EngineCandidate,
    EvaluationMetric,
    EvaluationRecord,
    GenerationManifest,
    GenerationRecord,
    IndexRef,
    RankedHit,
    RetrievalRequest,
    RetrievalResult,
    VectorAuthorityRef,
    canonical_digest,
)
from .protocols import (
    GenerationCatalog,
    RetrievalAuthorizationAdapter,
    RetrievalCache,
    RetrievalEngineAdapter,
)
from .repository import InMemoryGenerationCatalog, InMemoryRetrievalCache
from .service import GenerationLifecycle, GovernedRetriever

__all__ = [
    "ArtifactRef",
    "AuthorizationEvidence",
    "ChunkRef",
    "CitationRecord",
    "CitationRef",
    "CleanupCheckpoint",
    "CleanupIncompleteError",
    "DocumentRef",
    "EmbeddingModelRef",
    "EngineCandidate",
    "EvaluationMetric",
    "EvaluationRecord",
    "GenerationCatalog",
    "GenerationConflictError",
    "GenerationLifecycle",
    "GenerationManifest",
    "GenerationNotFoundError",
    "GenerationRecord",
    "GovernedRetriever",
    "IndexRef",
    "InMemoryGenerationCatalog",
    "InMemoryRetrievalCache",
    "MAX_CITATIONS",
    "MAX_EVALUATION_METRICS",
    "MAX_HITS",
    "MAX_INDEX_CHUNKS",
    "RankedHit",
    "RetrievalAuthorizationAdapter",
    "RetrievalAuthorizationError",
    "RetrievalCache",
    "RetrievalDomainError",
    "RetrievalEngineAdapter",
    "RetrievalReplayError",
    "RetrievalRequest",
    "RetrievalResult",
    "StaleGenerationError",
    "VectorAuthorityRef",
    "canonical_digest",
]
