"""Economics and SLO control-plane domain contracts.

The package is deliberately a pure typed boundary.  Collectors may profile raw
telemetry outside this package, but only bounded facts, opaque evidence refs,
versioned price cards, and append-only corrections can cross into the authority.
"""

from .models import (
    AllocationRef,
    DimensionRef,
    EconomicsConflict,
    EconomicsContractError,
    KeysetCursor,
    LateEventDecision,
    LateEventRejected,
    MetricKind,
    MetricTotal,
    PriceCard,
    PriceRate,
    ReconciliationReport,
    RetentionPolicy,
    SampleRef,
    SliKind,
    SloObjective,
    SloReadPage,
    SloReadRequest,
    SloWindowRollup,
    TenantReadScope,
    TenantScopeError,
    UsageCorrection,
    UsageFact,
    UsageReadPage,
    UsageReadRequest,
    UsageTombstone,
    UsageWindow,
    Watermark,
    WatermarkPolicy,
    WindowAggregate,
    WindowGranularity,
    content_digest,
)
from .repository import (
    AppendDisposition,
    AppendReceipt,
    EconomicsRepository,
    InMemoryEconomicsRepository,
    RepositoryUnavailable,
)
from .service import (
    aggregate_daily_from_hours,
    aggregate_usage,
    build_slo_rollup,
    decide_late_event,
    reconcile_samples,
    usage_query_digest,
    window_for,
)

__all__ = [
    "AllocationRef",
    "AppendDisposition",
    "AppendReceipt",
    "DimensionRef",
    "EconomicsConflict",
    "EconomicsContractError",
    "EconomicsRepository",
    "InMemoryEconomicsRepository",
    "KeysetCursor",
    "LateEventDecision",
    "LateEventRejected",
    "MetricKind",
    "MetricTotal",
    "PriceCard",
    "PriceRate",
    "ReconciliationReport",
    "RepositoryUnavailable",
    "RetentionPolicy",
    "SampleRef",
    "SliKind",
    "SloObjective",
    "SloReadPage",
    "SloReadRequest",
    "SloWindowRollup",
    "TenantReadScope",
    "TenantScopeError",
    "UsageCorrection",
    "UsageFact",
    "UsageReadPage",
    "UsageReadRequest",
    "UsageTombstone",
    "UsageWindow",
    "Watermark",
    "WatermarkPolicy",
    "WindowAggregate",
    "WindowGranularity",
    "aggregate_daily_from_hours",
    "aggregate_usage",
    "build_slo_rollup",
    "content_digest",
    "decide_late_event",
    "reconcile_samples",
    "usage_query_digest",
    "window_for",
]
