"""Public operation-registry contract for GraphOS surfaces and generators."""

from .digest import canonical_op, canonical_registry, registry_digest
from .registry import Caller, Invoke, PolicyDecision, Registry, authorized
from .scopes import (
    DOMAIN_SCOPE_CLASSES,
    FinanceScope,
    FleetScope,
    LoopsScope,
    OpsScope,
)
from .spec import (
    AuditClass,
    Composite,
    Confirm,
    Effect,
    EgMethod,
    EgSchemaRef,
    Executor,
    HttpShape,
    Idempotency,
    OpSpec,
    PrincipalRule,
    Stability,
    SubjectRef,
    SubjectSource,
    Surface,
    Verb,
)

__all__ = [
    "DOMAIN_SCOPE_CLASSES",
    "AuditClass",
    "Caller",
    "Composite",
    "Confirm",
    "Effect",
    "EgMethod",
    "EgSchemaRef",
    "Executor",
    "FinanceScope",
    "FleetScope",
    "HttpShape",
    "Idempotency",
    "Invoke",
    "LoopsScope",
    "OpSpec",
    "OpsScope",
    "PolicyDecision",
    "PrincipalRule",
    "Registry",
    "Stability",
    "SubjectRef",
    "SubjectSource",
    "Surface",
    "Verb",
    "authorized",
    "canonical_op",
    "canonical_registry",
    "registry_digest",
]
