"""GRAPHOS-DEPLOY-R003: pre-push hook shim audit never silently passes.

A hook-audit test invokes the generated pre-push shim text and confirms it
is treated as a failure -- never ok/skip -- when it is missing, does not
invoke pre-commit, has no --config reference, or references a configuration
path that does not resolve under the repository root.
"""

from __future__ import annotations

from graph_os.deployment import doctor as D

_REAL_SHIM = """#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-push)
exec pre-commit "${ARGS[@]}"
"""


def test_missing_hook_is_a_failure(tmp_path):
    result = D.audit_prepush_shim(None, repo_root=tmp_path)
    assert result["status"] == "fail"
    assert "no pre-push hook" in result["detail"]


def test_shim_that_does_not_invoke_precommit_is_a_failure(tmp_path):
    result = D.audit_prepush_shim("#!/bin/sh\nexit 0\n", repo_root=tmp_path)
    assert result["status"] == "fail"
    assert "does not invoke pre-commit" in result["detail"]


def test_shim_missing_config_reference_is_a_failure(tmp_path):
    shim = "#!/bin/sh\nexec pre-commit hook-impl --hook-type=pre-push\n"
    result = D.audit_prepush_shim(shim, repo_root=tmp_path)
    assert result["status"] == "fail"
    assert "no --config reference" in result["detail"]


def test_relocated_config_path_is_a_failure_not_silent_pass(tmp_path):
    """The verification case named in requirements.md: a relocated config."""
    result = D.audit_prepush_shim(_REAL_SHIM, repo_root=tmp_path)
    assert result["status"] == "fail"
    assert "does not resolve" in result["detail"]
    assert result["data"]["config_exists"] is False


def test_resolvable_config_executes_the_configured_gates(tmp_path):
    (tmp_path / ".pre-commit-config.yaml").write_text("repos: []\n")
    result = D.audit_prepush_shim(_REAL_SHIM, repo_root=tmp_path)
    assert result["status"] == "ok"
    assert result["data"] == {
        "installed": True,
        "config_path": ".pre-commit-config.yaml",
        "config_exists": True,
    }


def test_check_prepush_hook_is_wired_into_the_doctor_checks_table():
    assert D.CHECKS["prepush_hook"] is D._check_prepush_hook


def test_check_prepush_hook_reads_this_repositorys_real_shim_or_skips(tmp_path):
    """Live path: on a checkout with hooks installed this is ok; otherwise the
    check degrades to skip/fail, never raises."""
    result = D._check_prepush_hook()
    assert result["status"] in {"ok", "fail", "skip"}
    assert isinstance(result["detail"], str)
