name: Pages

on:
  push:
    branches:
      - main
    paths:
      - pages/**
      - overrides/**
      - mkdocs.yml
      - .github/workflows/pages.yml
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: Knuckles-Team/pipelines/.github/workflows/pages_pipeline.yml@fe4d11323d0b94c044c38f5257a15576c076500e
    with:
      content_source: pages
      shared_theme_enabled: true
