name: Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: Knuckles-Team/pipelines/.github/workflows/pages_pipeline.yml@main
    with:
      content_source: docs
      shared_theme_enabled: true
      spec_dashboard_enabled: true
      spec_dashboard_config: .github/spec-dashboard.json
